fix: correct AWS credentials configuration and enhance APK download process in CI workflow

diff --git a/.github/workflows/CI build.yml b/.github/workflows/CI build.yml
--- a/.github/workflows/CI build.yml
+++ b/.github/workflows/CI build.yml
@@ -133,9 +133,9 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-region: ${{ secrets.AWS_REGION }}
 
       - name: Download Android Artifact
         uses: actions/download-artifact@v4  
@@ -155,6 +155,7 @@ jobs:
           mv "$APK_FILE" "./downloaded-artifacts/$NEW_APK_NAME"
           aws s3 cp "./downloaded-artifacts/$NEW_APK_NAME" s3://${{ secrets.S3_BUCKET_NAME }}/android/${NEW_APK_NAME} --acl private
 
+  # Automated testing with Appium
   appium-tests-android:
     needs: [amazon-emulator]
     runs-on: macos-latest
@@ -163,18 +164,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Configure AWS credentails
+      - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+              aws-region: ${{ secrets.AWS_REGION }}
 
       - name: Download APK from S3
         run: |
             mkdir -p app
-            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/android/AppEds.apk --recursive --exclude "*" --include "*.apk"
-            mv AppEds.apk ./app/app-release.apk
+            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/android/ ./app --recursive --exclude "*" --include "*.apk"
+            
+            echo "Downloaded APK files list:"
+            ls -lh ./app/*.apk
+
+            APK_FILE=$(ls ./app/*.apk | head -n 1)
+            echo "File detected"
+
+            mv "$APK_FILE" ./app/app-release.apk
 
       - name: Install Node and Appium
         uses: actions/setup-node@v4
@@ -195,9 +203,10 @@ jobs:
           profile: Pixel_4
           script: |
             echo "Installing APK"
-            adb install ./app/app-release.apk
+            adb install ./app/app-release.apk || { echo "APK installation failed"; exit 1; }
             echo "Starting Appium"
             nohup appium &
+            sleep 5
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v2
